In [35]:
# Imports and pip installations (if needed)
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
import sklearn
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
import sklearn
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

# Part 1: Load the dataset

In [36]:
from sklearn.datasets import load_iris
# Load the dataset (load remotely, not locally)
iris_data = load_iris()

In [23]:
# Output the first 15 rows of the data
iris_df.rename(columns = {'Sepal Width' : '0'})
iris_df.head(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
6                 4.6               3.4                1.4               0.3
7                 5.0               3.4                1.5               0.2
8                 4.4               2.9                1.4               0.2
9                 4.9               3.1                1.5               0.1
10                5.4               3.7                1.5               0.2
11                4.8               3.4                1.6               0.2
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2

In [24]:
# Display a summary of the table information (number of datapoints, etc.)
iris_df.info() # for summary
iris_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

# Part 2: Split the dataset into train and test

In [39]:
# Take the dataset and split it into our features (X) and label (y)
features = iris_data['data']
labels = iris_data["target"]
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=3)
x_train

array([[5. , 3.5, 1.3, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [7.7, 3. , 6.1, 2.3],
       [5.7, 2.5, 5. , 2. ],
       [4.4, 3.2, 1.3, 0.2],
       [6.2, 2.8, 4.8, 1.8],
       [6.8, 3. , 5.5, 2.1],
       [6.9, 3.1, 5.1, 2.3],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.9, 1.7, 0.4],
       [7.2, 3.6, 6.1, 2.5],
       [6.1, 2.6, 5.6, 1.4],
       [5.8, 2.7, 4.1, 1. ],
       [4.9, 2.4, 3.3, 1. ],
       [6.7, 3.1, 4.7, 1.5],
       [5.8, 4. , 1.2, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [6.6, 2.9, 4.6, 1.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.7, 3. , 5. , 1.7],
       [4.5, 2.3, 1.3, 0.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.2, 2.2, 4.5, 1.5],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.7, 3.9, 1.2],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 3.2, 4.5, 1.5],
       [5.1, 3.3, 1.7, 0.5],
       [6. , 2.7, 5.1, 1.6],
       [5.8, 2.7, 5.1, 1.9],
       [5.4, 3

In [40]:
y_train

array([0, 1, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1,
       0, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2,
       1, 0, 0, 2, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 0, 2, 2, 2, 1, 1, 1, 0,
       0, 2, 2, 1, 2, 1, 2, 0, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 2,
       0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 2, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2,
       0, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0,
       0, 2, 2])

# Part 3: Logistic Regression

In [42]:
# i. Use sklearn to train a LogisticRegression model on the training set
clf = LogisticRegression(solver='lbfgs', max_iter=5000)
clf.fit(x_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
clf.predict_proba(x_test[:1])
# iv. Extract the coefficents and intercepts for the boundary line(s)

array([[9.80420178e-01, 1.95797885e-02, 3.35642357e-08]])

In [43]:
# iii. Report on the scorere for Logistic regression model, what does the score measure?
clf.score(x_test, y_test)

1.0

In [44]:
# iv. Extract the coefficents and intercepts for the boundary line(s
clf.coef_

array([[-0.39957359,  0.96280849, -2.44294589, -1.05204225],
       [ 0.5145811 , -0.30964545, -0.19490967, -0.94533212],
       [-0.11500751, -0.65316304,  2.63785556,  1.99737437]])

# Part 4: Support Vector Machine

In [46]:
# i. Use sklearn to train a Support Vector Classifier on the training set
clf1 = svm.SVC(probability=True)
clf1.fit(x_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
clf1.predict_proba(x_test[:1])

array([[0.97204226, 0.01835048, 0.00960726]])

In [47]:
# iii. Report on the score for the SVM, what does the score measure?
clf1.score(x_test, y_test)
y_test

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2])

# Part 5: Neural Network

In [57]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
clf2 = MLPClassifier(hidden_layer_sizes=(100,100,100,100),max_iter=1000)
clf2.fit(x_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
clf2.predict_proba(x_test[:1])

array([[9.99997329e-01, 2.67076675e-06, 8.02000750e-13]])

In [53]:
# iii. Report on the score for the Neural Network, what does the score measure?
clf2.score(x_test, y_test)

1.0

In [58]:
# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)
MLP1 = MLPClassifier(hidden_layer_sizes=(1),max_iter=2000)
MLP1.fit(x_train, y_train)
MLP1.score(x_test, y_test)

0.3333333333333333

In [59]:
MLP2 = MLPClassifier(hidden_layer_sizes=(1,1,1),max_iter=2000)
MLP2.fit(x_train, y_train)
MLP2.score(x_test, y_test)

0.4666666666666667

In [64]:
MLP3 = MLPClassifier(hidden_layer_sizes=(5),max_iter=2000)
MLP3.fit(x_train, y_train)
MLP3.score(x_test, y_test)

0.7333333333333333

In [71]:
MLP4 = MLPClassifier(hidden_layer_sizes=(5,5,5),max_iter=2000)
MLP4.fit(x_train, y_train)
MLP4.score(x_test, y_test)

1.0

In [73]:
MLP5 = MLPClassifier(hidden_layer_sizes=(5),max_iter=2000,activation="logistic")
MLP5.fit(x_train, y_train)
MLP5.score(x_test, y_test)

1.0

In [67]:
MLP6 = MLPClassifier(hidden_layer_sizes=(5), activation="logistic", max_iter=5000, solver="sgd", learning_rate="adaptive")
MLP6.fit(x_train, y_train)
MLP6.score(x_test, y_test)

0.8

In [ ]:
best configuration 

In [74]:
max(MLP1.score(x_test, y_test), MLP2.score(x_test, y_test),MLP3.score(x_test, y_test),MLP4.score(x_test, y_test),MLP5.score(x_test, y_test),MLP6.score(x_test, y_test))

1.0

# Part 6: K-Nearest Neighbors

In [80]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
clf3 = KNeighborsClassifier()
clf3.fit(x_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
clf3.predict_proba(x_test[:1])

array([[1., 0., 0.]])

In [79]:
# iii. Report on the score for kNN, what does the score measure?
clf3.score(x_test, y_test)

1.0

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

I think the logistic regression model performs best on this set of data all scores are the same and the dialectical model with the correct label is the second highest among all models. Through neural virtualization, it requires fewer parameters to train the network model. It does not require space like the K-nearest neighbor model.